# Generated by Django 4.0.5 on 2022-07-09 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.blogpost'),
        ),
    ]
