# Generated by Django 4.0.5 on 2022-07-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_rename_title_comments_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='slug',
            new_name='title',
        ),
    ]
