# Generated by Django 4.0.5 on 2022-07-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_rename_title_comments_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='slug',
            new_name='blogpost',
        ),
    ]
